// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnwR6fQ26aTOXZxmvgxqb3ZLFl7UewcUs',
    appId: '1:207960171476:web:37a431b75e1f47ca892c41',
    messagingSenderId: '207960171476',
    projectId: 'hk-medical-237cc',
    authDomain: 'hk-medical-237cc.firebaseapp.com',
    storageBucket: 'hk-medical-237cc.appspot.com',
    measurementId: 'G-73PLBX2V1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyBTdG_hW8MpjH3KywAc5UaG803Q7N_GI',
    appId: '1:207960171476:android:d170eb5f6064e3cf892c41',
    messagingSenderId: '207960171476',
    projectId: 'hk-medical-237cc',
    storageBucket: 'hk-medical-237cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIG0fynVz_NkmKrz_3iIaETyuGgEKCwWU',
    appId: '1:207960171476:ios:c885ad56a619ad3e892c41',
    messagingSenderId: '207960171476',
    projectId: 'hk-medical-237cc',
    storageBucket: 'hk-medical-237cc.appspot.com',
    androidClientId: '207960171476-ntmii1447l6835ps68dsquh0bc0dq43m.apps.googleusercontent.com',
    iosClientId: '207960171476-bj2t4m3qr5lauf4299m95r6l7bd5554p.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusRide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIG0fynVz_NkmKrz_3iIaETyuGgEKCwWU',
    appId: '1:207960171476:ios:c885ad56a619ad3e892c41',
    messagingSenderId: '207960171476',
    projectId: 'hk-medical-237cc',
    storageBucket: 'hk-medical-237cc.appspot.com',
    androidClientId: '207960171476-ntmii1447l6835ps68dsquh0bc0dq43m.apps.googleusercontent.com',
    iosClientId: '207960171476-bj2t4m3qr5lauf4299m95r6l7bd5554p.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusRide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnwR6fQ26aTOXZxmvgxqb3ZLFl7UewcUs',
    appId: '1:207960171476:web:f4e485423a9da6d9892c41',
    messagingSenderId: '207960171476',
    projectId: 'hk-medical-237cc',
    authDomain: 'hk-medical-237cc.firebaseapp.com',
    storageBucket: 'hk-medical-237cc.appspot.com',
    measurementId: 'G-6LVB6FYZHL',
  );
}
